assignment4
Arsture/waffle-rookies-19.5-react-assignment-1 pull request #3
Opened 2021-11-02 14:48 UTC by Arsture

2021-11-04 17:08 UTC, Arsture commented
과제 완료하였습니다.

2021-11-05 06:36 UTC, woohm402 requested changes
`SL-05` 오류입니다

수고하셨습니다. 조기제출이시니 넘어가고, 고쳐서 올려주시면 통과처리해드리겠습니다 :)

2021-11-05 06:36 UTC, woohm402 commented on README.md
>  <https://d9ctbp0kbdoj.cloudfront.net/index.html> - CDN <br>
CDN 말고 CloudFront가 맞는 표현일 것 같습니다.

CloudFront라는 서비스를 통해 배포되는 사이트를 CDN을 통하게 한 거니까요

2021-11-05 06:36 UTC, woohm402 commented on package.json
> +    "node-sass": "^6.0.1",
sass 써주세요 어제 톡방에서 말씀드렸는데ㅠㅜ

2021-11-05 06:36 UTC, woohm402 commented on src/App.css
> +} */
날려도 되지 않을까요?

2021-11-05 06:36 UTC, woohm402 commented on src/App.js
> +                            exact
details 에 이걸 넘길 필요가 없을 거 같아요

그리고 selectedStudent state는 HomePage 에 있는 게 맞을 거 같은데 어떠신가요?

2021-11-05 06:36 UTC, woohm402 commented on src/component/Details/StudentComments/Comment/Comment.js
> +`;
가독성 해치니까 `./Comment.style.js` 등으로 옮기는 게 좋습니다

2021-11-05 06:36 UTC, woohm402 commented on src/component/Details/StudentComments/Comment/Comment.js
> +    }, 500);
500은 좀 긴거같기도 합니다

2021-11-05 06:36 UTC, woohm402 commented on src/component/Details/StudentComments/Comment/Comment.js
> +            commentBody.current.clientHeight + commentBody.current.scrollTop >= commentBody.current.scrollHeight - 20 &&
20 좀 적을거같긴 해요 스크롤이 중간에 끊길거같아요

2021-11-05 06:36 UTC, woohm402 commented on src/component/Details/StudentComments/StudentHandler/Confirm.js
> +            .delete(`https://g5imzjo8qf.execute-api.ap-northeast-2.amazonaws.com/v1/student/${params.id}`, {
baseURL 적용하시면 신세계

2021-11-05 06:36 UTC, woohm402 commented on src/component/Details/StudentComments/StudentHandler/StudentHandler.js
> +                }).then(() => setSelectedStudent({ ...selectedStudent, locked: false }));
await이랑 then을 같이 쓰는 건 그리 흔한 패턴은 아닙니다..

async 사용했으면 좀더 깔끔하게 쓸 수 있습니다!

2021-11-05 06:36 UTC, woohm402 commented on src/component/Login/Login.module.scss
> +}
이래서 프리티어 쓰는 게 좋습니다!

2021-11-05 06:36 UTC, woohm402 commented on src/component/Login/Login.module.scss
> +}
마지막줄엔 항상 newLine 이 있는 게 좋아요

2021-11-05 06:36 UTC, woohm402 commented on src/context/Context.tsx
> +export const AuthProvider = ({ children }: { children: React.ReactNode | any }) => {
좀 지식자랑 같은 코멘트지만 이게 좀더 편하실 거예요

```suggestion
export const AuthProvider: React.FC = ({ children }) => {
```

2021-11-06 02:25 UTC, Arsture commented on README.md
>  <https://d9ctbp0kbdoj.cloudfront.net/index.html> - CDN <br>
넵!

2021-11-06 02:28 UTC, Arsture commented on package.json
> +    "node-sass": "^6.0.1",
`npm install -g sass`로 설치하였는데 완료된건가요??

2021-11-06 02:29 UTC, Arsture commented on src/App.css
> +} */
아,,, 놓쳤습니다,,, 삭제하겠습니당

2021-11-06 02:29 UTC, woohm402 commented on package.json
> +    "node-sass": "^6.0.1",
글로벌 말고 그냥 `npm install sass` 해주시면 됩니다!

2021-11-06 02:32 UTC, Arsture commented on src/App.js
> +                            exact
details에 `exact`를 넘길 필요가 없다는 뜻인가요??
그리고 `selectedStudent` state는 HomePage, Details 모두 쓰여서,,, App.js에 놔두었습니다

2021-11-06 02:39 UTC, Arsture commented on src/component/Details/StudentComments/Comment/Comment.js
> +`;
아,,, 그런 방법이 있었군요! `./Comment.style.js`로 옮기겠슴니당

2021-11-06 02:40 UTC, Arsture commented on src/component/Details/StudentComments/Comment/Comment.js
> +    }, 500);
50으로 조정하였습니닷

2021-11-06 02:40 UTC, Arsture commented on src/component/Details/StudentComments/Comment/Comment.js
> +            commentBody.current.clientHeight + commentBody.current.scrollTop >= commentBody.current.scrollHeight - 20 &&
그럼 50정도면 괜찮을까요?

2021-11-06 03:08 UTC, Arsture commented on src/component/Details/StudentComments/StudentHandler/Confirm.js
> +            .delete(`https://g5imzjo8qf.execute-api.ap-northeast-2.amazonaws.com/v1/student/${params.id}`, {
와 `defaluts` 값으로 여러 설정하니깐,,, 신세계네요... 감사합니당

2021-11-06 03:12 UTC, Arsture commented on src/component/Details/StudentComments/StudentHandler/StudentHandler.js
> +                }).then(() => setSelectedStudent({ ...selectedStudent, locked: false }));
생각해보니 async을 썼는데 왜 저기에 then을 썼을까요,,, 고쳤습니당

2021-11-06 03:13 UTC, Arsture commented on src/component/Login/Login.module.scss
> +}
js는 설정하니 자동으로 되던데 css는 안되더라구요,,, 이것도 따로 프리티어 css관련해서 설정해야겠죠??

2021-11-06 03:16 UTC, Arsture commented on src/context/Context.tsx
> +export const AuthProvider = ({ children }: { children: React.ReactNode | any }) => {
아하 벨로퍼트분께서 React.FC는 안쓰는 걸 추천한다길래,,, 근데 children이 디폴트로 들어가 있으니 이럴 때 편하네요!

2021-11-06 03:20 UTC, Arsture commented
@woohm402 
`SL-05`오류라 하셨는데, 아래와 같이 오류가 없는 것 같습니다...?
![image](https://user-images.githubusercontent.com/87017787/140596238-f3b63a42-3b33-4dc9-ac2e-69455a395087.png)

2021-11-06 03:21 UTC, Arsture commented on package.json
> +    "node-sass": "^6.0.1",
넵 알겠습니다!

2021-11-06 03:27 UTC, woohm402 commented on src/context/Context.tsx
> +export const AuthProvider = ({ children }: { children: React.ReactNode | any }) => {
ㅋㅋㅋㅋㅋ 상당한 논쟁거리입니다

2021-11-06 03:28 UTC, woohm402 commented on src/component/Login/Login.module.scss
> +}
css도 될걸요...?

2021-11-06 03:28 UTC, woohm402 commented on src/component/Details/StudentComments/Comment/Comment.js
> +            commentBody.current.clientHeight + commentBody.current.scrollTop >= commentBody.current.scrollHeight - 20 &&
전 한 500 두긴 합니다!

2021-11-06 03:28 UTC, woohm402 commented on src/App.js
> +                            exact
엥 Details에 selectedStudent 가 쓰이나요..? 🤔

2021-11-06 03:35 UTC, Arsture commented on src/App.js
> +                            exact
사실 details에서 선택된 학생을 selectedStudent로 설정하였는데 하나더 state를 만드는게 나을 거 같고 homepage로 selectedStudent를 옮기는 게 나을 것 같습니다. state를 다른 용도?로 중복사용 하였네요. 이렇게 고치는 게 나을까요??

2021-11-06 03:36 UTC, woohm402 commented on src/App.js
> +                            exact
넵!

사실 details에 필요한 student는 프사 전공 이름 전화번호 등 모든 데이터가 있는 친구고 HomePage에서 필요한 건 프사 이름 학년만 있으면 되니 분리하는 게 맞을 것 같아요

2021-11-06 03:44 UTC, Arsture commented on src/component/Login/Login.module.scss
> +}
히엥,,, 근데 왜 css scss 같은 파일확장자는 저장하였을 때 자동 정렬이 안될까요...? JS는 잘됩니다!

2021-11-06 03:50 UTC, Arsture commented on src/App.js
> +                            exact
넵 그런데 state이름은 중복되어도 되나요? 하위 컴포넌트가 아닌 다른 컴포넌트에 같은 이름의 state를 써도 기능상은 문제가 없을 것 같은데,,, 그래도 공동작업에 문제가 생길 것 같습니다! 다른사람이 이해하지 못할 수도 있을 것 같구,,,
제가 여쭤보고 싶은 건 같은 이름의 state를 써도 기능상에 문제가 없나요?

2021-11-06 05:10 UTC, Arsture commented
위의 프리티어 관련 질문 외에 모두 고쳤습니다! commit 해서 검사맡을까요??

2021-11-06 05:11 UTC, woohm402 commented
> @woohm402 위의 프리티어 관련 질문 외에 모두 고쳤습니다! commit 해서 검사맡을까요??

`SL-05` 고쳐졌는지 확인이 안되는데 고치고 배포까지 하셨나요?

2021-11-06 05:14 UTC, Arsture commented
> > @woohm402 위의 프리티어 관련 질문 외에 모두 고쳤습니다! commit 해서 검사맡을까요??
> 
> `SL-05` 고쳐졌는지 확인이 안되는데 고치고 배포까지 하셨나요?

아니요! 방금 배포 완료하였습니다!

2021-11-06 05:49 UTC, woohm402 commented
@Arsture 확인되었습니다! 👍

2021-11-06 05:49 UTC, woohm402 approved these changes

2021-11-06 05:51 UTC, Arsture commented
> @Arsture 확인되었습니다! 👍

commit/push 후 merge 할까요??

2021-11-06 05:53 UTC, woohm402 commented
> > @Arsture 확인되었습니다! 👍
> 
> commit/push 후 merge 할까요??

넵넵 하시면 됩니다! 과제 5 진행하시라고 레포 초대도 드렸으니 받아주세요 :+1:

2021-11-06 09:00 UTC, merged